/'
 ' File: activity-diag-eth.pu
 ' Project: img
 ' Author: Javier Reyes
 ' Created on: 31.08.2018
 ' 
 ' Last modified: 08.09.2018
 ' Modified by: Javier Reyes (javier.reyes.g@gmail.com)
 ' 
 ' MIT License
 ' 
 ' Copyright (c) 2018 Javier Reyes
 ' 
 ' Permission is hereby granted, free of charge, to any person obtaining a copy of
 ' this software and associated documentation files (the "Software"), to deal in
 ' the Software without restriction, including without limitation the rights to
 ' use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 ' of the Software, and to permit persons to whom the Software is furnished to do
 ' so, subject to the following conditions:
 ' 
 ' The above copyright notice and this permission notice shall be included in all
 ' copies or substantial portions of the Software.
 ' 
 ' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 ' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 ' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 ' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 ' SOFTWARE.
 '/

@startuml
start

:validate argument;

:create socket;
if (socketCreated?) then (no)
    stop
endif

:config sockAddress;
:bind socket to port;
if (socketBinded?) then (no)
    stop
endif

while (connection?) is (idle)
    :wait;
endwhile (connected)

:get client address;
:accept client;
if (connectionOK?) then (no)
    stop
endif

while (readData) is (not null)
    :as;
endwhile

if (readData?) then (0)
    :clientDisconnected;
else (-1)
    :errorReceived;
endif

end
@enduml